### ISSUE TITLE
AWS Lambda publish new version and update alias not using instance credentials

### ISSUE THREAD

**Issue by arfsb** [XT-i/aws-lambda-jenkins-plugin#68] opened 2017-03-16 05:00 UTC
When using the the 'AWS Lambda publish new version and update alias' post-build action, it does not seem like the 'Use instance credentials' option is being respected.  If I check this option and leave the AWS Access Key Id and AWS Secret Key blank, I am getting the following exception:

<pre>
ERROR: Build step failed with exception
com.amazonaws.services.lambda.model.AWSLambdaException: The security token included in the request is invalid. (Service: AWSLambda; Status Code: 403; Error Code: UnrecognizedClientException;)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1545)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1183)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:964)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:676)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:650)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:633)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$300(AmazonHttpClient.java:601)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:583)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:447)
	at com.amazonaws.services.lambda.AWSLambdaClient.doInvoke(AWSLambdaClient.java:1955)
	at com.amazonaws.services.lambda.AWSLambdaClient.invoke(AWSLambdaClient.java:1931)
	at com.amazonaws.services.lambda.AWSLambdaClient.getAlias(AWSLambdaClient.java:858)
	at com.xti.jenkins.plugin.awslambda.service.LambdaPublishService.publishLambda(LambdaPublishService.java:29)
	at com.xti.jenkins.plugin.awslambda.publish.LambdaPublisher.publish(LambdaPublisher.java:25)
	at com.xti.jenkins.plugin.awslambda.callable.PublishCallable.call(PublishCallable.java:39)
	at com.xti.jenkins.plugin.awslambda.callable.PublishCallable.call(PublishCallable.java:19)
	at hudson.remoting.LocalChannel.call(LocalChannel.java:45)
	at com.xti.jenkins.plugin.awslambda.publish.LambdaPublishPublisher.perform(LambdaPublishPublisher.java:63)
Caused: java.lang.RuntimeException
	at com.xti.jenkins.plugin.awslambda.publish.LambdaPublishPublisher.perform(LambdaPublishPublisher.java:72)
	at com.xti.jenkins.plugin.awslambda.publish.LambdaPublishPublisher.perform(LambdaPublishPublisher.java:47)
	at hudson.tasks.BuildStepMonitor$3.perform(BuildStepMonitor.java:45)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)
	at hudson.model.Run.execute(Run.java:1753)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:405)
Build step 'AWS Lambda publish new version and update alias' marked build as failure
</pre>

Also, when going back to configure the Jenkins project, the 'Use instance credentials' option is not saved.

**Comment by cast** [comment] 2017-03-19 11:07
Hi @arfsb , thank you for the report.

The problem was caused by a missing DataBoundSetter annotation on the instanceCredentials boolean.

It will be resolved in the next release, which should be available on March 20.

**Closed** 2017-03-19 11:20 UTC
