### ISSUE TITLE
Lambda executor doesn't find request handler class when uploading zip file artifact from workspace

### ISSUE THREAD

**Issue by mazoni** [XT-i/aws-lambda-jenkins-plugin#60] opened 2017-01-20 18:34 UTC
The plugin outputs as if my build was successfully, although when I run the lambda function my handler class is not found. 

`16:28:51 Lambda update code request:
16:28:51 {FunctionName: sc-assoc-units-worker,ZipFile: java.nio.HeapByteBuffer[pos=0 lim=15350954 cap=15350954],Publish: false}
 `

This was working a couple days ago just fine and now, with no changes to the job it suddenly stopped working. Still wondering if that is a plugin issue or an AWS change in the service.

Let me know if everything is still working fine for you please.
Thank you

**Comment by cast** [comment] 2017-01-24 22:44
Hi Mazoni, could you add some more details to this issue.

The response given by AWS might be helpful.

**Comment by cast** [comment] 2017-03-04 20:44
Closing due to unable to reproduce.

**Closed by cast** 2017-03-04 20:44 UTC
